In [1]:
import pandas
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
train_dataframe = pandas.read_csv('train.csv')
train_dataframe.head()

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,1,60,RL,65.0,8450,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2008,WD,Normal,208500
1,2,20,RL,80.0,9600,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,5,2007,WD,Normal,181500
2,3,60,RL,68.0,11250,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,9,2008,WD,Normal,223500
3,4,70,RL,60.0,9550,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2006,WD,Abnorml,140000
4,5,60,RL,84.0,14260,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,12,2008,WD,Normal,250000

In [13]:
for c in train_dataframe.columns[1:]:
    ratio = train_dataframe[c].isnull().sum() / train_dataframe[c].size
    if ratio > 0.0:
        print('%s: %.02e' %(c,ratio))

LotFrontage: 1.77e-01
Alley: 9.38e-01
MasVnrType: 5.48e-03
MasVnrArea: 5.48e-03
BsmtQual: 2.53e-02
BsmtCond: 2.53e-02
BsmtExposure: 2.60e-02
BsmtFinType1: 2.53e-02
BsmtFinType2: 2.60e-02
Electrical: 6.85e-04
FireplaceQu: 4.73e-01
GarageType: 5.55e-02
GarageYrBlt: 5.55e-02
GarageFinish: 5.55e-02
GarageQual: 5.55e-02
GarageCond: 5.55e-02
PoolQC: 9.95e-01
Fence: 8.08e-01
MiscFeature: 9.63e-01

In [19]:
train_dataframe.dropna(axis=1, how='any', inplace=True)
train_dataframe.head()

,Id,MSSubClass,MSZoning,LotArea,Street,LotShape,LandContour,Utilities,LotConfig,LandSlope,...,EnclosedPorch,3SsnPorch,ScreenPorch,PoolArea,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,1,60,RL,8450,Pave,Reg,Lvl,AllPub,Inside,Gtl,...,0,0,0,0,0,2,2008,WD,Normal,208500
1,2,20,RL,9600,Pave,Reg,Lvl,AllPub,FR2,Gtl,...,0,0,0,0,0,5,2007,WD,Normal,181500
2,3,60,RL,11250,Pave,IR1,Lvl,AllPub,Inside,Gtl,...,0,0,0,0,0,9,2008,WD,Normal,223500
3,4,70,RL,9550,Pave,IR1,Lvl,AllPub,Corner,Gtl,...,272,0,0,0,0,2,2006,WD,Abnorml,140000
4,5,60,RL,14260,Pave,IR1,Lvl,AllPub,FR2,Gtl,...,0,0,0,0,0,12,2008,WD,Normal,250000

In [21]:
class_labels={}
for c in ('MSZoning', 'Street', 'LotShape', 'LandContour', 'Utilities', 'LotConfig', 'LandSlope'):
    class_labels[c] = train_dataframe[c].unique()

In [23]:
for (k,v) in class_labels:
    print('%s: %s' % (k,v))

ValueError: too many values to unpack (expected 2)